# Generated by Django 2.2.8 on 2020-03-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CftaException',
            fields=[
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='', max_length=2, verbose_name='Select Language Field')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta_annex', models.BooleanField(default=False, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.BooleanField(default=False, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.BooleanField(default=False, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.BooleanField(default=False, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.BooleanField(default=False, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.BooleanField(default=False, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.BooleanField(default=False, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.BooleanField(default=False, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.BooleanField(default=False, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.BooleanField(default=False, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.BooleanField(default=False, verbose_name='CPTPP Chapter 15-A Section D')),
                ('cfta', models.BooleanField(default=False, verbose_name='CFTA Chapter 5')),
                ('name', models.TextField(default='-', unique=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommodityCodeSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='', max_length=2, verbose_name='Select Language Field')),
                ('commodity_code_system', models.CharField(default='', max_length=128, unique=True, verbose_name='Commodity Code System')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommodityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='', max_length=2, verbose_name='Select Language Field')),
                ('commodity_type', models.CharField(default='', max_length=128, unique=True, verbose_name='Commodity Type')),
            ],
            options={
                'unique_together': {('commodity_type', 'lang')},
            },
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='', max_length=2, verbose_name='Select Language Field')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta_annex', models.BooleanField(default=False, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.BooleanField(default=False, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.BooleanField(default=False, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.BooleanField(default=False, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.BooleanField(default=False, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.BooleanField(default=False, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.BooleanField(default=False, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.BooleanField(default=False, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.BooleanField(default=False, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.BooleanField(default=False, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.BooleanField(default=False, verbose_name='CPTPP Chapter 15-A Section D')),
                ('cfta', models.BooleanField(default=False, verbose_name='CFTA Chapter 5')),
                ('name', models.CharField(default='', max_length=128, unique=True, verbose_name='Entities')),
                ('tc', models.BooleanField(default=False, verbose_name='Department of Transport')),
                ('weapons_rule', models.BooleanField(default=False, verbose_name='Defence RCMP or CCG')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='', max_length=2, verbose_name='Select Language Field')),
                ('name', models.TextField(default='-', unique=True, verbose_name='Instructions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TAException',
            fields=[
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='', max_length=2, verbose_name='Select Language Field')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta_annex', models.BooleanField(default=False, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.BooleanField(default=False, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.BooleanField(default=False, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.BooleanField(default=False, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.BooleanField(default=False, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.BooleanField(default=False, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.BooleanField(default=False, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.BooleanField(default=False, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.BooleanField(default=False, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.BooleanField(default=False, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.BooleanField(default=False, verbose_name='CPTPP Chapter 15-A Section D')),
                ('cfta', models.BooleanField(default=False, verbose_name='CFTA Chapter 5')),
                ('name', models.TextField(default='-', unique=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenderingReason',
            fields=[
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='', max_length=2, verbose_name='Select Language Field')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta_annex', models.BooleanField(default=False, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.BooleanField(default=False, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.BooleanField(default=False, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.BooleanField(default=False, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.BooleanField(default=False, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.BooleanField(default=False, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.BooleanField(default=False, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.BooleanField(default=False, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.BooleanField(default=False, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.BooleanField(default=False, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.BooleanField(default=False, verbose_name='CPTPP Chapter 15-A Section D')),
                ('cfta', models.BooleanField(default=False, verbose_name='CFTA Chapter 5')),
                ('name', models.TextField(default='-', unique=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValueThreshold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta_annex', models.IntegerField(default=0, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.IntegerField(default=0, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.IntegerField(default=0, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.IntegerField(default=0, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.IntegerField(default=0, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.IntegerField(default=0, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.IntegerField(default=0, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.IntegerField(default=0, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.IntegerField(default=0, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.IntegerField(default=0, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.IntegerField(default=0, verbose_name='CPTPP Chapter 15-A Section D')),
                ('cfta', models.IntegerField(default=0, verbose_name='CFTA Chapter 5')),
                ('type_value', models.ForeignKey(default='', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityType', to_field='commodity_type', verbose_name='Commodity Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('lang', models.CharField(choices=[('EN', 'English'), ('FR', 'Francais')], default='', max_length=2, verbose_name='Select Language Field')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta_annex', models.BooleanField(default=False, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.BooleanField(default=False, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.BooleanField(default=False, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.BooleanField(default=False, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.BooleanField(default=False, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.BooleanField(default=False, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.BooleanField(default=False, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.BooleanField(default=False, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.BooleanField(default=False, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.BooleanField(default=False, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.BooleanField(default=False, verbose_name='CPTPP Chapter 15-A Section D')),
                ('cfta', models.BooleanField(default=False, verbose_name='CFTA Chapter 5')),
                ('code', models.CharField(db_column='code_list', default='', max_length=128, verbose_name='Code List')),
                ('code_system', models.ForeignKey(default='', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityCodeSystem', to_field='commodity_code_system', verbose_name='Commodity Code System')),
                ('type', models.ForeignKey(default='', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityType', to_field='commodity_type', verbose_name='Commodity Type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
