# Generated by Django 2.2.7 on 2019-12-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericTradeAgreements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta_annex', models.BooleanField(default=False, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.BooleanField(default=False, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.BooleanField(default=False, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.BooleanField(default=False, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.BooleanField(default=False, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.BooleanField(default=False, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.BooleanField(default=False, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.BooleanField(default=False, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.BooleanField(default=False, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.BooleanField(default=False, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.BooleanField(default=False, verbose_name='CPTPP Chapter 15-A Section D')),
            ],
        ),
        migrations.CreateModel(
            name='GenericCodesModel',
            fields=[
                ('generictradeagreements_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.GenericTradeAgreements')),
                ('gsin_class', models.CharField(default='', max_length=12, verbose_name='GSIN Class (4)')),
                ('gsin_code', models.CharField(default='', max_length=12, verbose_name='GSIN Code')),
                ('gsin_desc_en', models.CharField(default='', max_length=128, verbose_name='GSIN Code Description (English)')),
                ('gsin_desc_fr', models.CharField(default='', max_length=128, verbose_name='GSIN Code Description (Français)')),
                ('unspsc_code', models.CharField(default='', max_length=12, verbose_name='UNSPSC Code')),
                ('unspsc_code_desc_en', models.CharField(default='', max_length=128, verbose_name='UNSPSC Code Description (English)')),
                ('unspsc_code_desc_fr', models.CharField(default='', max_length=128, verbose_name='UNSPSC Code Description (Français)')),
            ],
            bases=('guide.generictradeagreements',),
        ),
        migrations.CreateModel(
            name='TenderingReasons',
            fields=[
                ('generictradeagreements_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.GenericTradeAgreements')),
                ('desc_en', models.TextField(default='-', unique=True, verbose_name='Description (English)')),
                ('desc_fr', models.TextField(default='_', unique=True, verbose_name='Description (Français)')),
            ],
            bases=('guide.generictradeagreements',),
        ),
        migrations.CreateModel(
            name='ConstructionCodes',
            fields=[
                ('genericcodesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.GenericCodesModel')),
                ('fs_code', models.CharField(default='', max_length=10, verbose_name='Federal Supply Code')),
                ('fs_code_desc', models.CharField(default='', max_length=128, verbose_name='Federal Supply Code Description')),
            ],
            bases=('guide.genericcodesmodel',),
        ),
        migrations.CreateModel(
            name='GoodsCodes',
            fields=[
                ('genericcodesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.GenericCodesModel')),
                ('fs_code', models.CharField(default='', max_length=10, verbose_name='Federal Supply Code')),
                ('fs_code_desc', models.CharField(default='', max_length=128, verbose_name='Federal Supply Code Description')),
            ],
            bases=('guide.genericcodesmodel',),
        ),
        migrations.CreateModel(
            name='ServicesCodes',
            fields=[
                ('genericcodesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.GenericCodesModel')),
                ('nafta_code', models.CharField(default='', max_length=12, verbose_name='NAFTA Common Classification System Codes')),
            ],
            bases=('guide.genericcodesmodel',),
        ),
    ]
