# Generated by Django 2.2.8 on 2020-03-08 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanTradeAgreement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta', models.BooleanField(default=False, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.BooleanField(default=False, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.BooleanField(default=False, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.BooleanField(default=False, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.BooleanField(default=False, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.BooleanField(default=False, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.BooleanField(default=False, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.BooleanField(default=False, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.BooleanField(default=False, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.BooleanField(default=False, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.BooleanField(default=False, verbose_name='CPTPP Chapter 15-A Section D')),
                ('cfta', models.BooleanField(blank=True, default=False, verbose_name='Canadian Free Trade Agreement (CFTA)')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityCodingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_en', models.CharField(default='-', max_length=128, unique=True, verbose_name='Commodity Code System (English)')),
                ('system_fr', models.CharField(default='_', max_length=128, unique=True, verbose_name='Commodity Code System (Français)')),
            ],
        ),
        migrations.CreateModel(
            name='CommodityTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_en', models.CharField(default='-', max_length=128, unique=True, verbose_name='Commodity Type (English)')),
                ('type_fr', models.CharField(default='_', max_length=128, unique=True, verbose_name='Commodity Type (Français)')),
            ],
        ),
        migrations.CreateModel(
            name='NumericTradeAgreements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta', models.IntegerField(default=0, verbose_name='NAFTA Annex 1001.1b-1')),
                ('ccfta', models.IntegerField(default=0, verbose_name='Chile (CCFTA) Annex K bis-01.1-3')),
                ('ccofta', models.IntegerField(default=0, verbose_name='Colombia (CCoFTA) Annex 1401-4')),
                ('chfta', models.IntegerField(default=0, verbose_name='Honduras (CHFTA) Annex 17.3')),
                ('cpafta', models.IntegerField(default=0, verbose_name='Panama (CPaFTA) Annex 4')),
                ('cpfta', models.IntegerField(default=0, verbose_name='Peru (CPFTA) Annex 1401. 1-3')),
                ('ckfta', models.IntegerField(default=0, verbose_name='Korea (CKFTA) Annex 14-A')),
                ('cufta', models.IntegerField(default=0, verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.IntegerField(default=0, verbose_name='WTO-AGP Canada Annex 1')),
                ('ceta', models.IntegerField(default=0, verbose_name='CETA Annex 19-4')),
                ('cptpp', models.IntegerField(default=0, verbose_name='CPTPP Chapter 15-A Section D')),
                ('cfta', models.BooleanField(blank=True, default=False, verbose_name='Canadian Free Trade Agreement (CFTA)')),
            ],
        ),
        migrations.CreateModel(
            name='TAUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_id', models.TextField(default='-', unique=True, verbose_name='Trade Agreement')),
                ('url_en', models.TextField(default='-', unique=True, verbose_name='URL (English)')),
                ('url_fr', models.TextField(default='-', unique=True, verbose_name='URL (Français)')),
            ],
        ),
        migrations.CreateModel(
            name='TextTradeAgreements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nafta', models.TextField(default='', verbose_name='NAFTA Article 1016')),
                ('ccfta', models.TextField(default='', verbose_name='Chile (CCFTA) Annex K bis-09')),
                ('ccofta', models.TextField(default='', verbose_name='Colombia (CCoFTA) Annex 1409')),
                ('chfta', models.TextField(default='', verbose_name='Honduras (CHFTA) Annex 17.11')),
                ('cpafta', models.TextField(default='', verbose_name='Panama (CPaFTA) Article 16.10')),
                ('cpfta', models.TextField(default='', verbose_name='Peru (CPFTA) Article 1409')),
                ('ckfta', models.TextField(default='', verbose_name='Korea (CKFTA) Article 14.3 (WTO)')),
                ('cufta', models.TextField(default='', verbose_name='Ukraine (CUFTA) Annex 10-3')),
                ('wto_agp', models.TextField(default='', verbose_name='WTO-AGP Article XV ')),
                ('ceta', models.TextField(default='', verbose_name='CETA 19.12')),
                ('cptpp', models.TextField(default='', verbose_name='CPTPP  Article 15.10 (2)')),
                ('cfta', models.TextField(default='', verbose_name='Canadian Free Trade Agreement (CFTA)')),
            ],
        ),
        migrations.CreateModel(
            name='CftaExceptions',
            fields=[
                ('texttradeagreements_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.TextTradeAgreements')),
                ('desc_en', models.TextField(default='-', unique=True, verbose_name='Reason (English)')),
                ('desc_fr', models.TextField(default='_', unique=True, verbose_name='Reason (Français)')),
            ],
            bases=('guide.texttradeagreements',),
        ),
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('booleantradeagreement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.BooleanTradeAgreement')),
                ('desc_en', models.TextField(default='-', unique=True, verbose_name='Description (English)')),
                ('desc_fr', models.TextField(default='_', unique=True, verbose_name='Description (Français)')),
            ],
            bases=('guide.booleantradeagreement',),
        ),
        migrations.CreateModel(
            name='TenderingReason',
            fields=[
                ('booleantradeagreement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.BooleanTradeAgreement')),
                ('desc_en', models.TextField(default='-', unique=True, verbose_name='Description (English)')),
                ('desc_fr', models.TextField(default='_', unique=True, verbose_name='Description (Français)')),
            ],
            bases=('guide.booleantradeagreement',),
        ),
        migrations.CreateModel(
            name='ValueThreshold',
            fields=[
                ('numerictradeagreements_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.NumericTradeAgreements')),
                ('type_value_en', models.ForeignKey(default='', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityTypes', to_field='type_en', verbose_name='Commodity Type Value Field (English)')),
                ('type_value_fr', models.ForeignKey(default='', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityTypes', to_field='type_fr', verbose_name='Commodity Type Value Field (Français)')),
            ],
            bases=('guide.numerictradeagreements',),
        ),
        migrations.CreateModel(
            name='TAException',
            fields=[
                ('booleantradeagreement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.BooleanTradeAgreement')),
                ('desc_en', models.TextField(default='-', unique=True, verbose_name='Description (English)')),
                ('desc_fr', models.TextField(default='_', unique=True, verbose_name='Description (Français)')),
            ],
            options={
                'unique_together': {('desc_en', 'desc_fr')},
            },
            bases=('guide.booleantradeagreement',),
        ),
        migrations.CreateModel(
            name='CommodityCode',
            fields=[
                ('booleantradeagreement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.BooleanTradeAgreement')),
                ('commodity_code_en', models.CharField(default='-', max_length=128, unique=True, verbose_name='Commodity Code System (English)')),
                ('commodity_code_fr', models.CharField(default='-', max_length=128, unique=True, verbose_name='Commodity Code System (Français)')),
                ('commodity_code_system_en', models.ForeignKey(default='-', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityCodingSystem', to_field='system_en', verbose_name='Commodity Code System Foreign Field (English)')),
                ('commodity_code_system_fr', models.ForeignKey(default='-', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityCodingSystem', to_field='system_fr', verbose_name='Commodity Code System Foreign Field (Français)')),
                ('commodity_type_en', models.ForeignKey(default='-', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityTypes', to_field='type_en', verbose_name='Commodity Type Foreign Field (English)')),
                ('commodity_type_fr', models.ForeignKey(default='_', max_length=128, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='guide.CommodityTypes', to_field='type_fr', verbose_name='Commodity Type Foreign Field (Français)')),
            ],
            bases=('guide.booleantradeagreement',),
        ),
    ]
