# Generated by Django 2.2.7 on 2019-12-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genericcodesmodel',
            options={'ordering': ['gsin_class', 'gsin_code']},
        ),
        migrations.AlterModelOptions(
            name='servicescodes',
            options={'ordering': ['nafta_code']},
        ),
    ]
