# Generated by Django 2.2.8 on 2020-02-06 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleantradeagreement',
            name='cfta',
            field=models.BooleanField(default=False, verbose_name='CFTA Chapter 5'),
        ),
        migrations.AddField(
            model_name='numerictradeagreements',
            name='cfta',
            field=models.IntegerField(default=0, verbose_name='CFTA Chapter 5'),
        ),
        migrations.CreateModel(
            name='GoodsMilitaryCode',
            fields=[
                ('booleantradeagreement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.BooleanTradeAgreement')),
                ('fs_code', models.CharField(default='', max_length=10, verbose_name='Federal Supply Code')),
                ('fs_code_desc', models.CharField(default='', max_length=128, verbose_name='Federal Supply Code Description')),
            ],
            options={
                'ordering': ['fs_code', 'fs_code_desc'],
                'unique_together': {('fs_code', 'fs_code_desc')},
            },
            bases=('guide.booleantradeagreement',),
        ),
        migrations.CreateModel(
            name='FederalEntities',
            fields=[
                ('booleantradeagreement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='guide.BooleanTradeAgreement')),
                ('name_en', models.TextField(default='-', unique=True, verbose_name='Name of Federal Entity (English)')),
                ('name_fr', models.TextField(default='_', unique=True, verbose_name='Name of Federal Entity (Français)')),
            ],
            options={
                'unique_together': {('name_en', 'name_fr')},
            },
            bases=('guide.booleantradeagreement',),
        ),
    ]
