# Generated by Django 2.2.7 on 2019-12-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20191212_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscodes',
            options={'ordering': ['fs_code', 'fs_code_desc']},
        ),
    ]
