# Generated by Django 2.2.8 on 2020-02-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_cfta_entities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsMilitaryCode',
        ),
    ]
