# Generated by Django 2.2.7 on 2019-12-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20191216_1643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goodscodes',
            unique_together={('fs_code', 'fs_code_desc')},
        ),
    ]
