const construction_codes = [
    "5111 Site investigation work",
    "5112 Demolition work",
    "5113 Site formation and clearance work",
    "5114 Excavating and earthmoving work",
    "5115 Site preparation work for mining",
    "5116 Scaffolding work",
    "5121 For one - and two - dwelling buildings",
    "5122 For multi - dwelling buildings",
    "5123 For warehouses and industrial buildings",
    "5124 For commercial buildings",
    "5125 For public entertainment buildings",
    "5126 For hotel, restaurant and similar buildings",
    "5127 For educational buildings",
    "5128 For health buildings",
    "5129 For other buildings",
    "5131 For highways (except elevated highways), streets, roads, railways and airfield runways",
    "5132 For bridges, elevated highways, tunnels and subways",
    "5133 For waterways, harbours, dams and other waterworks",
    "5134 For long distance pipelines, communication and power lines (cables)",
    "5135 For local pipelines and cables; ancillary works",
    "5136 For constructions for mining and manufacturing",
    "5137 For constructions for sport and recreation",
    "51371 For stadia and sports grounds",
    "51372 For other sport and recreation installations (e.g. swimming pools, tennis courts, golf courses)",
    "5139 For engineering works n.e.c.",
    "5140 Assembly and erection of prefabricated constructions",
    "5151 Foundation work (incl. pile driving)",
    "5152 Water well drilling",
    "5153 Roofing and water proofing",
    "5154 Concrete work",
    "5155 Steel bending and erection (incl. welding)",
    "5156 Masonry work",
    "5156 Masonry work",
    "5159 Other special trade construction work",
    "5161 Heating, ventilation and air conditioning work",
    "5163 Gas fitting construction work",
    "5164 Electrical work",
    "51641 Electrical wiring and fitting work",
    "51642 Fire alarm construction work",
    "51643 Burglar alarm system construction work",
    "51644 Residential antenna construction work",
    "51649 Other electrical construction work",
    "5165 Insulation work (electrical wiring, water, heat, sound)",
    "5166 Fencing and railing construction work",
    "5169 Other installation work",
    "51691 Lift and escalator construction work",
    "51699 Other installation work n.e.c.",
    "5171 Glazing work and window glass installation work",
    "5172 Plastering work",
    "5174 Floor and wall tiling work",
    "5175 Other floor laying, wall covering and wall papering work",
    "5176 Wood and metal joinery and carpentry work",
    "5177 Interior fitting decoration work",
    "5178 Ornamentation fitting work",
    "5179 Other building completion and finishing work",
    "5180 Renting services related to equipment for construction or demolition of buildings or civil engineering works, with operator"
];
